image: node:14.19.1

.restore_cache: &restore_cache
  before_script:
    - npm ci --cache .npm --prefer-offline

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm

stages:
  - setup
  - test
  - preview
  - staging
  - production
  - cleaning

# Setup stage jobs
install:
  stage: setup
  <<: *restore_cache
  script:
    - npm i
  only:
    - merge_requests
    - master
  except:
    - schedules

# Test stage jobs
# test:
#   stage: test
#   needs: ['install']
#   <<: *restore_cache
#   script:
#     - yarn test:ci
#   only:
#     - merge_requests
#     - master
#   except:
#     - schedules

lint:
  stage: test
  needs: ['install']
  <<: *restore_cache
  script:
    - yarn lint
  only:
    - merge_requests
    - master
  except:
    - schedules

# Review App
deploy_review:
  stage: preview
  needs: ['install', 'lint']
  dependencies:
    - install
    - lint
  <<: *restore_cache
  before_script:
    - chmod +x config/scripts/review.deployment.sh
    - export REVIEW_ENV_NAME="review-$(echo $CI_COMMIT_REF_SLUG | cut -d'-' -f1,2)"
  script:
    - echo $CI_MERGE_REQUEST_IID
    - echo $CI_COMMIT_REF_SLUG
    - echo $REVIEW_ENV_NAME
    - |
      VERCEL_ORG_ID=$VERCEL_ORG_ID \
      VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID \
      VERCEL_TOKEN=$VERCEL_TOKEN \
      CI_COMMIT_SHA=$CI_COMMIT_SHA \
      REVIEW_URL=review-pr-$CI_MERGE_REQUEST_IID.sniplink.tk \
      config/scripts/./review.deployment.sh
  environment:
    name: review-pr-$CI_MERGE_REQUEST_IID
    url: https://review-pr-$CI_MERGE_REQUEST_IID.sniplink.tk
    on_stop: destroy_review
    auto_stop_in: 1 hour
  only:
    - merge_requests

destroy_review:
  stage: preview
  needs: ['lint']
  before_script:
    - chmod +x config/scripts/bin/jq-linux
    - chmod +x config/scripts/review.destroy.sh
  script:
    - |
      VERCEL_TOKEN=$VERCEL_TOKEN \
      REVIEW_URL=review-pr-$CI_MERGE_REQUEST_IID.sniplink.tk \
      config/scripts/./review.destroy.sh
  when: manual
  environment:
    name: review-pr-$CI_MERGE_REQUEST_IID
    action: stop
  only:
    - merge_requests

# Staging stage jobs
deploy_stage:
  stage: staging
  needs: []
  <<: *restore_cache
  before_script:
    - chmod +x config/scripts/staging.deploy.sh
  script:
    - |
      VERCEL_ORG_ID=$VERCEL_ORG_ID \
      VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID \
      VERCEL_TOKEN=$VERCEL_TOKEN \
      CI_COMMIT_SHA=$CI_COMMIT_SHA \
      config/scripts/./staging.deploy.sh
  environment:
    name: stage
    url: https://stage.sniplink.tk
  when: manual
  only:
    - merge_requests

# Production stage jobs
deploy_prod:
  stage: production
  needs: []
  <<: *restore_cache
  before_script:
    - chmod +x config/scripts/production.deploy.sh
  script:
    - |
      VERCEL_ORG_ID=$VERCEL_ORG_ID \
      VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID \
      VERCEL_TOKEN=$VERCEL_TOKEN \
      CI_COMMIT_SHA=$CI_COMMIT_SHA \
      config/scripts/./production.deploy.sh
  environment:
    name: production
    url: https://sniplink.tk
  when: manual
  only:
    - merge_requests

clean_deployments:
  stage: cleaning
  needs: ['deploy_prod']
  <<: *restore_cache
  before_script:
    - chmod +x config/scripts/remove.deployments.js
  script:
    - |
      VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID \
      VERCEL_TOKEN=$VERCEL_TOKEN \
      config/scripts/remove.deployments.js
  only:
    - merge_request
