name: Install and Lint

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
# - uses: actions/github-script@v6
#   env:
#     REVIEW_APP_URL: https://review-pr-${{ github.event.number }}.sniplink.tk
#   with:
#     github-token: ${{secrets.GH_TOKEN}}
#     script: |
#       github.rest.issues.createComment({
#         issue_number: context.issue.number,
#         owner: context.repo.owner,
#         repo: context.repo.repo,
#         body: `🚀 Review app deployed at <${process.env.REVIEW_APP_URL}>`
#       })
