name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  call_install_build:
    uses: ./.github/workflows/install-lint.yml

  deploy_preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' }}
    needs: [call_install_build]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Deploy preview app
        run: |
          VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }} \
          VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} \
          VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} \
          CI_COMMIT_SHA=${{ github.sha }} \
          REVIEW_URL=review-pr-${{ github.event.number }}.sniplink.tk \
          sh ./src/config/scripts/review.deployment.sh

  # deploy_stage:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: staging
  #     url: https://stage.sniplink.tk

  #   needs: [build]

  #   strategy:
  #     matrix:
  #       node-version: [14.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - name: Deploy stage to Vercel
  #       run: |
  #         VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }} \
  #         VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} \
  #         VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} \
  #         CI_COMMIT_SHA=${{ github.sha }} \
  #         sh ./src/config/scripts/staging.deploy.sh
