name: Preview Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  call_install_build:
    uses: ./.github/workflows/install-lint.yml

  remove_preview:
    runs-on: ubuntu-latest
    if: ${{ (github.event.action == 'closed') && (github.event.pull_request.merged) }}
    needs: [call_install_build]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          chmod +x ./src/config/scripts/bin/jq-linux
      - name: Remove previous review app
        run: |
          VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} \
          REVIEW_URL=review-pr-${{ github.event.number }}.sniplink.tk \
          sh ./src/config/scripts/review.destroy.sh

  deploy_preview:
    runs-on: ubuntu-latest
    if: ${{ (github.event.action != 'closed') }}
    needs: [call_install_build]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Deploy preview app
        run: |
          VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }} \
          VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} \
          VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} \
          CI_COMMIT_SHA=${{ github.sha }} \
          REVIEW_URL=review-pr-${{ github.event.number }}.sniplink.tk \
          sh ./src/config/scripts/review.deployment.sh
      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          header: sniplink-review-app
          message: 🚀 Release review app ${{ github.sha }} to <https://review-pr-${{ github.event.number }}.sniplink.tk>
